#############################################################################
# Makefile for building: qt_osg
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? 11? 17 14:07:01 2017
# Project:  qt_osg.pro
# Template: app
# Command: d:\Environment\Qt\4.8.6win32vs2010\bin\qmake.exe -spec ..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\win32-msvc2010 -o Makefile qt_osg.pro
#############################################################################

first: debug
install: debug-install
uninstall: debug-uninstall
MAKEFILE      = Makefile
QMAKE         = d:\Environment\Qt\4.8.6win32vs2010\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		debug \
		release

debug: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: qt_osg.pro  ..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\win32-msvc2010\qmake.conf ..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\qconfig.pri \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\modules\qt_webkit_version.pri \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\qt_functions.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\qt_config.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\exclusive_builds.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\default_pre.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\default_pre.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\debug.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\debug_and_release.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\default_post.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\default_post.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\rtti.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\exceptions.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\stl.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\shared.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\embed_manifest_exe.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\embed_manifest_dll.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\warn_on.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\qt.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\opengl.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\thread.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\moc.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\windows.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\resources.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\uic.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\yacc.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\lex.prf \
		..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\include_source_dir.prf \
		d:\Environment\Qt\4.8.6win32vs2010\lib\qtmaind.prl
	$(QMAKE) -spec ..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\win32-msvc2010 -o Makefile qt_osg.pro
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\qconfig.pri:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\modules\qt_webkit_version.pri:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\qt_functions.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\qt_config.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\exclusive_builds.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\default_pre.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\default_pre.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\debug.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\debug_and_release.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\default_post.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\default_post.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\rtti.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\exceptions.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\stl.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\shared.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\embed_manifest_exe.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\embed_manifest_dll.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\warn_on.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\qt.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\opengl.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\thread.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\moc.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\win32\windows.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\resources.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\uic.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\yacc.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\lex.prf:
..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\features\include_source_dir.prf:
d:\Environment\Qt\4.8.6win32vs2010\lib\qtmaind.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ..\..\..\..\Environment\Qt\4.8.6win32vs2010\mkspecs\win32-msvc2010 -o Makefile qt_osg.pro

qmake_all: FORCE

make_default: debug-make_default release-make_default FORCE
make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
	-$(DEL_FILE) ".obj\qt_osg.intermediate.manifest"
	-$(DEL_FILE) bin\qt_osg.exp
	-$(DEL_FILE) bin\qt_osg.ilk
	-$(DEL_FILE) vc*.pdb
	-$(DEL_FILE) vc*.idb
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) bin\qt_osg.pdb

check: first

debug-mocclean: $(MAKEFILE).Debug
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean: $(MAKEFILE).Release
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables: $(MAKEFILE).Debug
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables: $(MAKEFILE).Release
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
